services:

  postgres:
    image: postgres:17
    container_name: postgres-db

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:

    build: .

    container_name: etl-pipeline

    depends_on:
      - postgres

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./sql:/app/sql
      - ./src:/app/src
      - ./logs:/app/logs

    command: python src/main.py

volumes:

  postgres_data: